MetaDataFormat: "yaml"

title: "睿"
baseURL: "https://z-rui.github.io/"
defaultContentLanguage: "zh"
theme: "hugo-xmin"

menu:
    main:
      - name: 首页
        url: ""
        weight: 1

params:
    footer: |
        &copy; 张睿 2015---{Year} | [GitHub](https://github.com/z-rui)

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        codeFences: false

# vim: ts=4:sw=4:et
